# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: az-api

on:
  push:
    branches: ["main"]
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
  install:
    runs-on: self-hosted
    needs: checkout
    strategy:
      matrix:
        dir: [.]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: ${{matrix.dir}}/package-lock.json
      - run: npm ci --prefix ${{matrix.dir}}
  build:
    runs-on: self-hosted
    needs: install
    steps:
      - run: npm run build --if-present
  pm2:
    runs-on: self-hosted
    needs: build
    steps:
      - run: pwd
      - run: npx --yes pm2@latest
        continue-on-error: true
      - run: npx pm2 ls -m | grep status"
        id: app_status
      - run: ${{ steps  }}
      - run: npx pm2 stop app
        continue-on-error: true
      - run: npx pm2 start ./dist/app.js --name app
      - run: npx pm2 save
      - run: npx pm2 startup
